/*
 * Created on 2026-01-03 ( Time 17:01:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.orange.messagerie.dao.entity;

import java.io.Serializable;

import lombok.*;

import jakarta.persistence.*;

import java.util.Date;



/**
 * Persistent class for entity stored in table "participant_conversation"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="participant_conversation" )
public class ParticipantConversation implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="recreated_at")
    private Date       recreatedAt  ;

    @Column(name="recreated_by")
    private Integer    recreatedBy  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="left_at")
    private Date       leftAt       ;

    @Column(name="left_by")
    private Integer    leftBy       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="definitively_left_at")
    private Date       definitivelyLeftAt ;

    @Column(name="definitively_left_by")
    private Integer    definitivelyLeftBy ;

    @Column(name="has_left")
    private Boolean    hasLeft      ;

    @Column(name="has_definitively_left")
    private Boolean    hasDefinitivelyLeft ;

    @Column(name="has_cleaned")
    private Boolean    hasCleaned   ;

    @Column(name="is_admin")
    private Boolean    isAdmin      ;

	// "conversationId" (column "conversation_id") is not defined by itself because used as FK in a link 
	// "userId" (column "user_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id")
    private User user        ;
    @ManyToOne
    @JoinColumn(name="conversation_id", referencedColumnName="id")
    private Conversation conversation;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ParticipantConversation() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
