/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package ci.orange.messagerie.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// CONVERSATION
	VIEW_CONVERSATION("VIEW_CONVERSATION"),	
	CREATE_CONVERSATION("CREATE_CONVERSATION"),
	UPDATE_CONVERSATION("UPDATE_CONVERSATION"),
	DELETE_CONVERSATION("DELETE_CONVERSATION"),
	// HISTORIQUE_SUPPRESSION_MESSAGE
	VIEW_HISTORIQUE_SUPPRESSION_MESSAGE("VIEW_HISTORIQUE_SUPPRESSION_MESSAGE"),	
	CREATE_HISTORIQUE_SUPPRESSION_MESSAGE("CREATE_HISTORIQUE_SUPPRESSION_MESSAGE"),
	UPDATE_HISTORIQUE_SUPPRESSION_MESSAGE("UPDATE_HISTORIQUE_SUPPRESSION_MESSAGE"),
	DELETE_HISTORIQUE_SUPPRESSION_MESSAGE("DELETE_HISTORIQUE_SUPPRESSION_MESSAGE"),
	// MESSAGE
	VIEW_MESSAGE("VIEW_MESSAGE"),	
	CREATE_MESSAGE("CREATE_MESSAGE"),
	UPDATE_MESSAGE("UPDATE_MESSAGE"),
	DELETE_MESSAGE("DELETE_MESSAGE"),
	// PARTICIPANT_CONVERSATION
	VIEW_PARTICIPANT_CONVERSATION("VIEW_PARTICIPANT_CONVERSATION"),	
	CREATE_PARTICIPANT_CONVERSATION("CREATE_PARTICIPANT_CONVERSATION"),
	UPDATE_PARTICIPANT_CONVERSATION("UPDATE_PARTICIPANT_CONVERSATION"),
	DELETE_PARTICIPANT_CONVERSATION("DELETE_PARTICIPANT_CONVERSATION"),
	// TYPE_CONVERSATION
	VIEW_TYPE_CONVERSATION("VIEW_TYPE_CONVERSATION"),	
	CREATE_TYPE_CONVERSATION("CREATE_TYPE_CONVERSATION"),
	UPDATE_TYPE_CONVERSATION("UPDATE_TYPE_CONVERSATION"),
	DELETE_TYPE_CONVERSATION("DELETE_TYPE_CONVERSATION"),
	// TYPE_MESSAGE
	VIEW_TYPE_MESSAGE("VIEW_TYPE_MESSAGE"),	
	CREATE_TYPE_MESSAGE("CREATE_TYPE_MESSAGE"),
	UPDATE_TYPE_MESSAGE("UPDATE_TYPE_MESSAGE"),
	DELETE_TYPE_MESSAGE("DELETE_TYPE_MESSAGE"),
	// USER
	VIEW_USER("VIEW_USER"),	
	CREATE_USER("CREATE_USER"),
	UPDATE_USER("UPDATE_USER"),
	DELETE_USER("DELETE_USER");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
